# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7k325tffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths {
  C:/fpga_ember/fpga_co/ip_repo/ISL58315_driver_1.0
  C:/fpga_dev/fpga_co/ip_repo/isl58315_driver_1.0
  c:/fpga_ember/fpga_co/ip_repo/isl58315_driver_1.0
} [current_fileset]

add_files C:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_lmb_bram_0/system_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_mdm_1_0/system_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/system_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/fpga_ember/fpga_co/gw/ep/projector_test_build.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib C:/fpga_ember/fpga_co/gw/src/projector_test_build_top.v
read_xdc C:/fpga_ember/fpga_co/gw/par/projector_test_build_top.xdc
set_property used_in_implementation false [get_files C:/fpga_ember/fpga_co/gw/par/projector_test_build_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/fpga_ember/fpga_co/gw/ep/projector_test_build.cache/wt [current_project]
set_property parent.project_dir C:/fpga_ember/fpga_co/gw/ep [current_project]
synth_design -top projector_test_build_top -part xc7k325tffg900-2
write_checkpoint projector_test_build_top.dcp
report_utilization -file projector_test_build_top_utilization_synth.rpt -pb projector_test_build_top_utilization_synth.pb
